# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Gluesys Co., Ltd.
apiVersion: daos.gluesys.com/v1alpha1
kind: DaosContainer
metadata:
  name: kv-cache
  namespace: default
spec:
  poolRef: p0
  type: POSIX
  fileOclass: RP_2GX
  chunkSize: 4194304
  checksum: crc32
