# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Gluesys Co., Ltd.
apiVersion: daos.gluesys.com/v1alpha1
kind: DaosPool
metadata:
  name: p0
spec:
  systemRef: daos-dev
  size: 1Ti
  redundancyFactor: 1
