apiVersion: daos.gluesys.com/v1alpha1
kind: DaosPool
metadata:
  labels:
    app.kubernetes.io/name: daos-operator
    app.kubernetes.io/managed-by: kustomize
  name: daospool-sample
spec:
  # TODO(user): Add fields here
