/*
SPDX-License-Identifier: Apache-2.0
Copyright 2026 Gluesys Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package render turns DaosSystem intent plus per-node facts into the three DAOS
// YAML files. It has no Kubernetes dependency so it can be tested as plain Go.
// The layout mirrors exastor/daos-images entrypoints (2.8 keys: server uses
// mgmt_svc_replicas, agent access_points, control hostlist).
package render

import (
	"bytes"
	"fmt"
	"text/template"
)

// Engine is one daos_engine on a node.
type Engine struct {
	Index       int
	Targets     int32
	Helpers     int32
	FabricIface string
	FabricPort  int32
	PinnedNuma  *int32
	ScmSizeGiB  int32
	Bdevs       []string
}

// ServerConfig is everything daos_server.yml needs for one node.
type ServerConfig struct {
	// Label names the owning DaosSystem in the generated header (defaults to SystemName).
	Label         string
	SystemName    string
	MsReplicas    []string
	Port          int32
	Provider      string
	NrHugepages   int32
	AllowInsecure bool
	// TelemetryPort > 0 enables the Prometheus endpoint on every engine host.
	TelemetryPort int32
	Engines       []Engine
}

const header = "# Generated by daos-operator for DaosSystem %s; edits are overwritten.\n"

var serverTmpl = template.Must(template.New("server").Parse(`name: {{.SystemName}}
mgmt_svc_replicas:
{{- range .MsReplicas}}
  - {{.}}
{{- end}}
port: {{.Port}}
provider: {{.Provider}}
nr_hugepages: {{.NrHugepages}}
disable_vfio: false
{{- if gt .TelemetryPort 0}}
telemetry_port: {{.TelemetryPort}}
{{- end}}
control_log_file: /var/log/daos/daos_server.log
control_metadata:
  path: /var/daos/control_metadata
transport_config:
  allow_insecure: {{.AllowInsecure}}
  client_cert_dir: /etc/daos/certs/clients
  ca_cert: /etc/daos/certs/daosCA.crt
  cert: /etc/daos/certs/server.crt
  key: /etc/daos/certs/server.key
engines:
{{- range .Engines}}
  - targets: {{.Targets}}
    nr_xs_helpers: {{.Helpers}}
    fabric_iface: {{.FabricIface}}
    fabric_iface_port: {{.FabricPort}}
{{- if .PinnedNuma}}
    pinned_numa_node: {{.PinnedNuma}}
{{- end}}
    log_file: /var/log/daos/daos_engine.{{.Index}}.log
    storage:
      - class: ram
        scm_mount: /mnt/daos{{.Index}}
        scm_size: {{.ScmSizeGiB}}
      - class: nvme
        bdev_list:
{{- range .Bdevs}}
          - "{{.}}"
{{- end}}
        bdev_roles: [wal, meta, data]
{{- end}}
`))

// Server renders daos_server.yml.
func Server(c ServerConfig) (string, error) {
	if c.SystemName == "" || len(c.MsReplicas) == 0 || len(c.Engines) == 0 {
		return "", fmt.Errorf("render: system name, mgmt_svc_replicas and at least one engine are required")
	}
	for _, e := range c.Engines {
		if e.FabricIface == "" || len(e.Bdevs) == 0 {
			return "", fmt.Errorf("render: engine %d needs fabric_iface and bdev_list", e.Index)
		}
	}
	label := c.Label
	if label == "" {
		label = c.SystemName
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, header, label)
	if err := serverTmpl.Execute(&b, c); err != nil {
		return "", err
	}
	return b.String(), nil
}

// Agent renders daos_agent.yml (2.8 still uses access_points here).
func Agent(systemName string, accessPoints []string, port int32, allowInsecure bool) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, header, systemName)
	fmt.Fprintf(&b, "name: %s\naccess_points:\n", systemName)
	for _, a := range accessPoints {
		fmt.Fprintf(&b, "  - %s\n", a)
	}
	fmt.Fprintf(&b, "port: %d\nruntime_dir: /var/run/daos_agent\nlog_file: /var/log/daos/daos_agent.log\n", port)
	fmt.Fprintf(&b, "transport_config:\n  allow_insecure: %t\n  ca_cert: /etc/daos/certs/daosCA.crt\n  cert: /etc/daos/certs/agent.crt\n  key: /etc/daos/certs/agent.key\n", allowInsecure)
	return b.String()
}

// Control renders daos_control.yml for dmg.
func Control(systemName string, hostlist []string, port int32, allowInsecure bool) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, header, systemName)
	fmt.Fprintf(&b, "name: %s\nhostlist:\n", systemName)
	for _, h := range hostlist {
		fmt.Fprintf(&b, "  - %s\n", h)
	}
	fmt.Fprintf(&b, "port: %d\ntransport_config:\n  allow_insecure: %t\n  ca_cert: /etc/daos/certs/daosCA.crt\n  cert: /etc/daos/certs/admin.crt\n  key: /etc/daos/certs/admin.key\n", port, allowInsecure)
	return b.String()
}
